#!/bin/sh

echo "                              .:'"
echo "                          _.::'"
echo "                .-;;-.   (_.'"
echo "               / ;;;' \\"
echo "              |.  \`:   | "
echo "               \:   \`;/"
echo "        jgs     '-..-'"
